services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  ui:
    build:
      context: ./ui
    ports:
      - "8080:80"
    depends_on:
      - backend